---
- name: Detect Public IP with Error Handling
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Detect public IP using external script
      shell: "{{ playbook_dir }}/../scripts/detect_ip.sh"
      register: ip_result
      failed_when: false
      changed_when: false

    - name: Fail if IP detection failed
      fail:
        msg: |
          🚨 IP Detection Failed!
          
          The system could not detect your public IP address.
          This is required for secure SSH and WireGuard access.
          
          To fix this:
          1. Check your internet connection
          2. Try running the setup again
          3. Or manually set your IP in ansible/group_vars/all.yml:
             allowed_ssh_cidrs: "YOUR_IP/32"
             allowed_wireguard_cidrs: "YOUR_IP/32"
          
          Example:
             allowed_ssh_cidrs: "203.0.113.10/32"
             allowed_wireguard_cidrs: "203.0.113.10/32"
      when: ip_result.rc != 0

    - name: Set detected IP variables
      set_fact:
        detected_ip: "{{ ip_result.stdout | regex_replace('\\s+', '') }}"
        allowed_ssh_cidrs: "{{ ip_result.stdout | regex_replace('\\s+', '') }}/32"
        allowed_wireguard_cidrs: "{{ ip_result.stdout | regex_replace('\\s+', '') }}/32"
        public_ip_detected: true

    - name: Display success message
      debug:
        msg: |
          ✅ Successfully detected your public IP: {{ detected_ip }}
          - SSH access will be restricted to: {{ allowed_ssh_cidrs }}
          - WireGuard access will be restricted to: {{ allowed_wireguard_cidrs }}